Technical Debt
pro100user15/bookstore pull request #11
Opened 2022-03-31 22:39 UTC by pro100user15

# Releted Issue
- closed #10 

# Proposed Changes
- Technical debt of my previous PR #5 and #8

# Additional Info

# Checklist
- [ ] Tests
- [ ] Documentation

# Screenshots

2022-04-03 13:34 UTC, dshma requested changes

2022-04-03 13:34 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/service/CategoryService.java
> +public interface CategoryService {
It seems now it would be better to always return books within the CategoryDTO so that the CategoryServiceImpl receives the CRUD methods from the BasicService (as now you'll need to implement them yourself)
If you don't need the number of books somewhere in the UI, just don't use, take what's required

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/App.tsx
> +            {/*<Container maxWidth="xl" sx={{marginTop: "64px", paddingTop: "10px"}}>*/}
here we go again

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/components/Categories/EditCategoryForm/EditCategoryForm.tsx
> +                    <h4>Редагування категорії</h4>
Let's go English

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/components/Header/Header.tsx
> +                        <NavLink to="/categories" className="link">Categories</NavLink>
same as for user role

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/components/RegistrationForms.tsx
> +                {/*<div>
do avoid committing commented code

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/components/RegistrationForms.tsx
> +                {/*<div>
do avoid committing commented code

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/components/RegistrationForms.tsx
> +export default RegistrationForms;
why Forms?

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/pages/ProfileEdit.tsx
> +            console.log(response);
avoid console logs

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/pages/ProfileEdit.tsx
> +            console.log(response);
avoid console logs

2022-04-03 13:34 UTC, dshma commented on bookstore-frontend/src/router/index.ts
> +            console.log(userRoutes);
avoid console logs

2022-04-03 18:44 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/BookstoreApplication.java
>  public class BookstoreApplication {
Okay

2022-04-03 18:46 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Order.java
> +    @Column(updatable = false)
@CreationTimestamp annotation will set the first value, and it is forbidden to change it later

2022-04-03 18:50 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Order.java
> +    @Column(updatable = false)
right, but this also means it cannot be null, there should be no way to save an order so that this value remains unpopulated

2022-04-03 18:53 UTC, pro100user15 commented on bookstore-frontend/src/components/Header/Header.tsx
> +                        <NavLink to="/categories" className="link">Categories</NavLink>
This is for a test. The user will not have access to edit categories

2022-04-03 18:54 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Order.java
> +    @Column(updatable = false)
nullable = false will translate into NOT NULL constraint, which is what should happen, without it (now) I can easily create a row with empty value in the createdAt column

2022-04-03 18:55 UTC, dshma commented on bookstore-frontend/src/components/Header/Header.tsx
> +                        <NavLink to="/categories" className="link">Categories</NavLink>
If something is for dev/test purposes, it shouldn't get committed like this

2022-04-03 20:58 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Order.java
> +    @Column(updatable = false)
I realized the mistake

2022-04-03 21:02 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/User.java
> +    @ElementCollection(targetClass = Role.class, fetch = FetchType.EAGER)
fetch type EAGER because Sprint Security extract roles when logging in and checking jwt

2022-04-03 21:04 UTC, pro100user15 commented on bookstore-frontend/src/components/RegistrationForms.tsx
> +export default RegistrationForms;
This is an old implementation of the registration form and not to be confused I changed the name (I will delete this file)

2022-04-09 20:02 UTC, dshma approved these changes

2022-04-09 20:02 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/BasicRepositoryImpl.java
> -        return sessionFactory.getCurrentSession()
why getCurrentSession doesn't satisfy you?
openSession requires flushing and closing the session object

2022-04-09 20:02 UTC, dshma approved these changes

2022-04-10 12:02 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/BasicRepositoryImpl.java
> +        T entity = sessionFactory.openSession().get(basicClass, id);
I tried to solve LazyInizializationExeption without a transaction, but now I understand why getCurrentSession and @Transaction over read method

2022-04-10 12:02 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/BasicRepositoryImpl.java
> -        return sessionFactory.getCurrentSession()
I tried to solve LazyInizializationExeption without a transaction, but now I understand why getCurrentSession and @Transaction over read method

2022-04-10 12:10 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/BasicRepositoryImpl.java
> -        return sessionFactory.getCurrentSession()
I have already changed to getCurrentTransaction

2022-04-10 12:10 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/BasicRepositoryImpl.java
> +        T entity = sessionFactory.openSession().get(basicClass, id);
I have already changed to getCurrentTransaction

2022-04-14 12:12 UTC, merged