Refactoring model structure
pro100user15/bookstore pull request #5
Opened 2022-03-22 11:16 UTC by pro100user15

- Create entity Address and Publishing
- Remove entity PublishingHouse, WorldLiterature and PeriodLiterature
- Status entity rewritten to Status enum

(And create base CRUD operation for new entities)

2022-03-24 13:20 UTC, RuslanSlobodian requested changes

2022-03-24 13:20 UTC, RuslanSlobodian commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Book.java
> -    @Max(value = 2022, message = "First edition year cannot be higher than 2022")
current year is used. what will be next year?

2022-03-24 15:07 UTC, RuslanSlobodian commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Basket.java
> +    private double totalPrice;
Price is better to save as a BigDecimal value

2022-03-24 15:13 UTC, RuslanSlobodian commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Book.java
> -    @Max(value = 2022, message = "First edition year cannot be higher than 2022")
if you use java.time.Year, you may set annotation @PastOrPresent

2022-03-24 15:45 UTC, RuslanSlobodian commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Address.java
> +    private List<User> users;
Setters for fields with annotation @ManyToMany and @OneToMany must be private:
Setter(AccessLevel.PRIVATE);

2022-03-24 15:46 UTC, RuslanSlobodian requested changes
Setters for fields with annotation @ManyToMany and @OneToMany must be private:
Setter(AccessLevel.PRIVATE);

2022-03-27 23:20 UTC, dshma requested changes

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Publishing.java
>      @Size(min = 1, max = 64, message = "Publishing house must be between 1 and 64 characters long")
still house

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Publishing.java
>      @NotEmpty(message = "Publishing house cannot be empty")
still house

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Publishing.java
>      @Size(min = 1, max = 64, message = "Publishing house must be between 1 and 64 characters long")
I don't think 64 characters is enough? Don't be greedy :)

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Address.java
> +    @OneToOne(mappedBy = "address")
avoid EAGER fetch type

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Publishing.java
> +    @OneToOne(targetEntity = Address.class)
avoid EAGER fetch type

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/User.java
> +    private LocalDateTime createdAt;
this column cannot be null, updatable and available for creation

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/AddressRepositoryImpl.java
> +    public AddressRepositoryImpl(SessionFactory sessionFactory) {
BasicRepositoryImpl already autowires this bean

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/PublishingRepositoryImpl.java
> +    public PublishingRepositoryImpl(SessionFactory sessionFactory) {
BasicRepositoryImpl already autowires this bean

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/AddressServiceImpl.java
> +    @Transactional(readOnly = true)
do you need a transaction here?

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/AddressServiceImpl.java
> +    public Address create(Address object) {
what is the purpose of the BasicService if you implement all CRUD methods in all impl services?

2022-03-27 23:20 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/AddressServiceImpl.java
> +        readById(object.getId());
validation should be extracted into a separate method

2022-03-27 23:28 UTC, dshma requested changes

2022-03-27 23:28 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/User.java
>      @Size(min = 2, max = 35, message = "Name must be between 2 and 35 characters long")
why 35 characters?)

2022-03-27 23:28 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/CategoryRepository.java
> +    Integer getBookSizeByCategoryName(Long id);
ByCategoryName but the parameter is ID

2022-03-27 23:28 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/CategoryRepositoryImpl.java
> +    //private String SELECT_CATEGORY_WITH_COUNT_BOOKS = "SELECT new com.pro100user.bookstore.entity.model.CategoryModel(id, name, books.size) from Category";
avoid commented code

2022-03-27 23:28 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/CategoryRepositoryImpl.java
> +        return (Integer) sessionFactory.getCurrentSession().createQuery(SELECT_COUNT_BOOKS)
wouldn't int be enough?

2022-03-27 23:28 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/CategoryRepositoryImpl.java
> +    /*@Override
avoid commented code

2022-03-27 23:28 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/CategoryRepositoryImpl.java
>      private String SELECT_BY_NAME = "FROM Category WHERE name like :name";
these class variables should be static final

2022-03-27 23:28 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/repository/impl/UserRepositoryImpl.java
> +        User user = sessionFactory.getCurrentSession().createQuery(findUserByLogin, User.class)
findUserByLogin should follow the constant's modifiers and naming convention

2022-03-27 23:28 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/service/BookService.java
> +    //TODO getListBookByCategoryName(String name);
avoid committing such code

2022-03-27 23:28 UTC, dshma commented on bookstore-frontend/src/router/index.ts
> +            console.log(guestRoutes);
avoid console logs

2022-03-27 23:29 UTC, dshma approved these changes

2022-03-27 23:44 UTC, pro100user15 commented on bookstore-frontend/src/router/index.ts
> +            console.log(guestRoutes);
I used them to derive intermediate results. I'll take them

2022-03-27 23:56 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Address.java
> +    Publishing publishing;
sorry I didn't notice

2022-03-29 11:59 UTC, merged