Refactoring backend
pro100user15/bookstore pull request #8
Opened 2022-03-28 08:53 UTC by pro100user15

# Releted Issue
- closed #7 

# Proposed Changes
- Added annotation "CurentUser"
- Add new ExceptionHandler
- Refactroing entities

# Additional Info
- any additional information or context

# Checklist
- [x] Added annotation "CurentUser"
- [x] Add new ExceptionHandler
- [x] Refactroing entities
- [ ] Using mappers at the service layer

2022-03-28 23:10 UTC, dshma requested changes

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java
> +    /*@Named("countBooks")
avoid committing commented code

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java
> +    //@Mapping(source = "books", target = "countBooks", qualifiedByName = "countBooks")
avoid committing commented code

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java
> +    //@Mapping(source = "books", target = "countBooks", qualifiedByName = "countBooks")
avoid committing commented code

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Book.java
> +    //@PastOrPresent(message = "Publication year cannot be higher than the current year")
I won't stop writing this until you stop committing commented code, this isn't acceptable within PRs unless there is a reason (which is clearly stated)

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/Category.java
>      @OneToMany(mappedBy = "category")
be consistent, if you explicitly state the fetch type LAZY for *ToMany annotations (even though it's the default fetch type), then follow this rule everywhere

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/model/User.java
> +    @Size(min = 3, max = 320, message = "Email must be between 3 and 320 characters long")
email can be 320 characters long while name and surname - 64, this is not fair :)

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/security/jwt/JwtProvider.java
> +            throw new JwtAuthenticationException("Jwt is valid!");
I suppose it should be "invalid" or "is not valid", shouldn't it?

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/CategoryServiceImpl.java
> +@Transactional(propagation = Propagation.REQUIRES_NEW)
not consistent with other services

2022-03-28 23:10 UTC, dshma commented on bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/UserServiceImpl.java
> +        User oldUser = readById(user.getId());
unused variable

2022-03-29 12:03 UTC, pro100user15 commented on bookstore-backend/src/main/java/com/pro100user/bookstore/controller/MainController.java
>      @GetMapping
We checked at what point the controllers are configured, because in one they were not configured.
This designer has already taken away

2022-03-29 12:16 UTC, merged